# Generated by Django 5.0.2 on 2024-03-31 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name_plural': 'Income'},
        ),
    ]
